import type { MapStyleElement } from 'react-native-maps';

export const darkMapStyle: MapStyleElement[] = [
  { elementType: 'geometry', stylers: [{ color: '#111214' }] },
  { elementType: 'labels.icon', stylers: [{ visibility: 'off' }] },
  { elementType: 'labels.text.fill', stylers: [{ color: '#6E737B' }] },
  { elementType: 'labels.text.stroke', stylers: [{ color: '#0E0F11' }] },
  { featureType: 'administrative', elementType: 'geometry', stylers: [{ color: '#26282C' }] },
  { featureType: 'administrative.land_parcel', stylers: [{ visibility: 'off' }] },
  { featureType: 'administrative.locality', elementType: 'labels.text.fill', stylers: [{ color: '#A4A9B1' }] },
  { featureType: 'administrative.neighborhood', elementType: 'labels.text.fill', stylers: [{ color: '#6E737B' }] },
  { featureType: 'poi', elementType: 'labels.text', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi', elementType: 'geometry', stylers: [{ color: '#15161A' }] },
  { featureType: 'poi.business', stylers: [{ visibility: 'off' }] },
  { featureType: 'poi.park', elementType: 'geometry', stylers: [{ color: '#132019' }] },
  { featureType: 'poi.park', elementType: 'labels.text', stylers: [{ visibility: 'on' }] },
  { featureType: 'poi.park', elementType: 'labels.text.fill', stylers: [{ color: '#4D6655' }] },
  { featureType: 'road', elementType: 'geometry.fill', stylers: [{ color: '#1E2023' }] },
  { featureType: 'road', elementType: 'geometry.stroke', stylers: [{ color: '#191A1D' }] },
  { featureType: 'road', elementType: 'labels.text.fill', stylers: [{ color: '#5A5F66' }] },
  { featureType: 'road.arterial', elementType: 'geometry', stylers: [{ color: '#26282C' }] },
  { featureType: 'road.highway', elementType: 'geometry', stylers: [{ color: '#26282C' }] },
  { featureType: 'road.highway', elementType: 'geometry.stroke', stylers: [{ color: '#191A1D' }] },
  { featureType: 'road.highway', elementType: 'labels.text.fill', stylers: [{ color: '#6E737B' }] },
  { featureType: 'road.local', elementType: 'labels', stylers: [{ visibility: 'off' }] },
  { featureType: 'transit', stylers: [{ visibility: 'off' }] },
  { featureType: 'water', elementType: 'geometry', stylers: [{ color: '#0C1116' }] },
  { featureType: 'water', elementType: 'labels.text.fill', stylers: [{ color: '#3C4047' }] },
];
